treatment_links = {
    "Apple Scab": "https://www2.gov.bc.ca/gov/content/industry/agriculture-seafood/animals-and-crops/plant-health/insects-and-plant-diseases/tree-fruits/apple-scab",
    "Apple Black Rot": "https://extension.umn.edu/plant-diseases/black-rot-apple",
    "Apple Cedar Rust": "https://extension.umn.edu/plant-diseases/cedar-apple-rust",
    "Apple Healthy": None,
    "Blueberry Healthy": None,
    "Cherry Healthy": None,
    "Cherry Powdery Mildew": "https://treefruit.wsu.edu/crop-protection/disease-management/cherry-powdery-mildew/",
    "Corn Cercospora": "https://extension.umn.edu/corn-pest-management/gray-leaf-spot-corn",
    "Corn Common Rust": "https://extension.umn.edu/corn-pest-management/common-rust-corn",
    "Corn Healthy": None,
    "Corn Northern Leaf Blight": "https://extension.umn.edu/corn-pest-management/northern-corn-leaf-blight",
    "Grape Black Rot": "https://www.gardeningknowhow.com/edible/fruits/grapes/black-rot-grape-treatment.htm",
    "Grape Esca": "https://grapes.extension.org/grapevine-measles/",
    "Grape Healthy": None,
    "Grape Leaf Blight": "https://www.planthealthaustralia.com.au/wp-content/uploads/2013/11/Bacterial-blight-of-grapevine-FS.pdf",
    "Orange Haunglongbing": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8636133/",
    "Peach Bacterial Spot": "https://www.aces.edu/blog/topics/crop-production/bacterial-spot-treatment-in-peaches/",
    "Peach Healthy": None,
    "Pepper Bacterial Spot": "https://extension.wvu.edu/lawn-gardening-pests/plant-disease/fruit-vegetable-diseases/bacterial-leaf-spot-of-pepper",
    "Pepper Healthy": None,
    "Potato Early Blight": "https://www.planetnatural.com/pest-problem-solver/plant-disease/early-blight/",
    "Potato Healthy": None,
    "Potato Late Blight": "https://www.planetnatural.com/pest-problem-solver/plant-disease/late-blight/",
    "Raspberry Healthy": None,
    "Squash Powdery Mildew": "https://www.gardeningknowhow.com/edible/vegetables/squash/powdery-mildew-in-squash.htm",
    "Soybean Healthy": None,
    "Strawberry Healthy": None,
    "Strawberry Leaf Scorch": "https://www.gardeningknowhow.com/edible/fruits/strawberry/strawberries-with-leaf-scorch.htm",
    "Tomato Bacterial Spot": "https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper",
    "Tomato Early Blight": "https://extension.umn.edu/disease-management/early-blight-tomato-and-potato",
    "Tomato Healthy": None,
    "Tomato Late Blight": "https://extension.wvu.edu/lawn-gardening-pests/plant-disease/fruit-vegetable-diseases/late-blight-tomatoes",
    "Tomato Leaf Mold": "https://www.lovethegarden.com/uk-en/article/tomato-leaf-mould",
    "Tomato Septoria Leaf Spot": "https://extension.wvu.edu/lawn-gardening-pests/plant-disease/fruit-vegetable-diseases/septoria-leaf-spot",
    "Tomato Spider Mites": "https://pnwhandbooks.org/insect/vegetable/vegetable-pests/hosts-pests/tomato-spider-mite",
    "Tomato Target Spot": "https://apps.lucidcentral.org/ppp/text/web_full/entities/tomato_target_spot_163.htm",
    "Tomato Mosaic Virus": "https://www.almanac.com/pest/mosaic-viruses",
    "Tomato Yellow Leaf Curl Virus": "https://plantix.net/en/library/plant-diseases/200036/tomato-yellow-leaf-curl-virus",
    # TODO change mocks
    "Aster": "mock",
    'Daisy': "mock",
    'Iris': "mock",
    'Lavender': "mock",
    'Lily': "mock",
    'Marigold': "mock",
    'Orchid': "mock",
    'Poppy': "mock",
    'Rose': "mock",
    'Sunflower': "mock"
}

growing_links = {
    "Apple Healthy": "https://www.almanac.com/plant/apples",
    "Blueberry Healthy": "https://extension.umn.edu/fruit/growing-blueberries-home-garden",
    "Cherry Healthy": "https://www.almanac.com/plant/cherries",
    "Corn Healthy": "https://www.almanac.com/plant/corn",
    "Grape Healthy": "https://www.rhs.org.uk/fruit/grapes/grow-your-own",
    "Peach Healthy": "https://www.masterclass.com/articles/how-to-grow-a-peach-tree-in-your-backyard",
    "Pepper Healthy": "https://bonnieplants.com/blogs/how-to-grow/growing-peppers",
    "Potato Healthy": "https://www.gardendesign.com/vegetables/potatoes.html",
    "Raspberry Healthy": None,
    "Soybean Healthy": None,
    "Strawberry Healthy": None,
    "Tomato Healthy": None,
    "Apple Scab": None,
    "Apple Black Rot": None,
    "Apple Cedar Rust": None,
    "Cherry Powdery Mildew": None,
    "Corn Cercospora": None,
    "Corn Common Rust": None,
    "Corn Northern Leaf Blight": None,
    "Grape Black Rot": None,
    "Grape Esca": None,
    "Grape Leaf Blight": None,
    "Orange Haunglongbing": None,
    "Peach Bacterial Spot": None,
    "Pepper Bacterial Spot": None,
    "Potato Early Blight": None,
    "Potato Late Blight": None,
    "Squash Powdery Mildew": None,
    "Strawberry Leaf Scorch": None,
    "Tomato Bacterial Spot": None,
    "Tomato Early Blight": None,
    "Tomato Late Blight": None,
    "Tomato Leaf Mold": None,
    "Tomato Septoria Leaf Spot": None,
    "Tomato Spider Mites": None,
    "Tomato Target Spot": None,
    "Tomato Mosaic Virus": None,
    "Tomato Yellow Leaf Curl Virus": None,
    "Aster": None,
    'Daisy': None,
    'Iris': None,
    'Lavender': None,
    'Lily': None,
    'Marigold': None,
    'Orchid': None,
    'Poppy': None,
    'Rose': None,
    'Sunflower': None
}

plant_class_names = [
    "Apple Scab",
    "Apple Black Rot",
    "Apple Cedar Rust",
    "Apple Healthy",
    "Blueberry Healthy",
    "Cherry Healthy",
    "Cherry Powdery Mildew",
    "Corn Cercospora",
    "Corn Common Rust",
    "Corn Healthy",
    "Corn Northern Leaf Blight",
    "Grape Black Rot",
    "Grape Esca",
    "Grape Healthy",
    "Grape Leaf Blight",
    "Orange Haunglongbing",
    "Peach Bacterial Spot",
    "Peach Healthy",
    "Pepper Bacterial Spot",
    "Pepper Healthy",
    "Potato Early Blight",
    "Potato Healthy",
    "Potato Late Blight",
    "Raspberry Healthy",
    "Soybean Healthy",
    "Squash Powdery Mildew",
    "Strawberry Healthy",
    "Strawberry Leaf Scorch",
    "Tomato Bacterial Spot",
    "Tomato Early Blight",
    "Tomato Healthy",
    "Tomato Late Blight",
    "Tomato Leaf Mold",
    "Tomato Septoria Leaf Spot",
    "Tomato Spider Mites",
    "Tomato Target Spot",
    "Tomato Mosaic Virus",
    "Tomato Yellow Leaf Curl Virus"
]

flower_class_names = [
    'Aster',
    'Daisy',
    'Iris',
    'Lavender',
    'Lily',
    'Marigold',
    'Orchid',
    'Poppy',
    'Rose',
    'Sunflower'
]

model_path = "model/resnet_model.h5"
flower_model_path = "model/flower_resnet_model.h5"

# TODO change hours
schedule = {
    "Apple Scab": {"hourly": 24},
    "Apple Black Rot": {"hourly": 24},
    "Apple Cedar Rust": {"hourly": 24},
    "Apple Healthy": {"hourly": 24},
    "Blueberry Healthy": {"hourly": 24},
    "Cherry Healthy": {"hourly": 24},
    "Cherry Powdery Mildew": {"hourly": 24},
    "Corn Cercospora": {"hourly": 24},
    "Corn Common Rust": {"hourly": 24},
    "Corn Healthy": {"hourly": 24},
    "Corn Northern Leaf Blight": {"hourly": 24},
    "Grape Black Rot": {"hourly": 24},
    "Grape Esca": {"hourly": 24},
    "Grape Healthy": {"hourly": 24},
    "Grape Leaf Blight": {"hourly": 24},
    "Orange Haunglongbing": {"hourly": 24},
    "Peach Bacterial Spot": {"hourly": 24},
    "Peach Healthy": {"hourly": 24},
    "Pepper Bacterial Spot": {"hourly": 24},
    "Pepper Healthy": {"hourly": 24},
    "Potato Early Blight": {"hourly": 24},
    "Potato Healthy": {"hourly": 24},
    "Potato Late Blight": {"hourly": 24},
    "Raspberry Healthy": {"hourly": 24},
    "Soybean Healthy": {"hourly": 24},
    "Squash Powdery Mildew": {"hourly": 24},
    "Strawberry Healthy": {"hourly": 24},
    "Strawberry Leaf Scorch": {"hourly": 24},
    "Tomato Bacterial Spot": {"hourly": 24},
    "Tomato Early Blight": {"hourly": 24},
    "Tomato Healthy": {"hourly": 24},
    "Tomato Late Blight": {"hourly": 24},
    "Tomato Leaf Mold": {"hourly": 24},
    "Tomato Septoria Leaf Spot": {"hourly": 24},
    "Tomato Spider Mites": {"hourly": 24},
    "Tomato Target Spot": {"hourly": 24},
    "Tomato Mosaic Virus": {"hourly": 24},
    "Tomato Yellow Leaf Curl Virus": {"hourly": 24},
    "Aster": {"hourly": 24},
    'Daisy': {"hourly": 24},
    'Iris': {"hourly": 24},
    'Lavender': {"hourly": 24},
    'Lily': {"hourly": 24},
    'Marigold': {"hourly": 24},
    'Orchid': {"hourly": 24},
    'Poppy': {"hourly": 24},
    'Rose': {"hourly": 24},
    'Sunflower': {"hourly": 24}
}
